# Generated by Django 4.2.1 on 2023-09-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.PositiveIntegerField()),
                ('curso', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=12, unique=True)),
                ('data_ingresso', models.DateField()),
                ('foto_aluno', models.ImageField(upload_to='alunos/')),
            ],
        ),
    ]
