# Generated by Django 4.2.1 on 2023-09-05 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.AutoField(default=datetime.datetime(2023, 9, 5, 1, 2, 21, 923447, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
